### ISSUE TITLE
ForScan Connection not working

### ISSUE THREAD

**Issue by markus2801** [EtoTen/stm32_can_sim#6]
Hey, thanks for your work mate.
Everything works fine, except that ForScan doesn't find the APIM. 
Of course I did it with an "real" profile as described, but no matter what CAN pins on the APIM i use, the connection doesnt work.
Anyone having the same issue?

APIM is from 2018

**Comment by svenhe88** [comment]
Hi, 
same problem.... tried different can bus, PINs, but ForScan always says "No connection to car"

Also APIM from 2018 (2 different ones) 

Do I need a BCM??

regards

**Comment by EtoTen** [comment]
I am attaching a profile I got from forscan support. Here is the original description for it: "Please find the profile attached. Please use it with last official beta v2.4.3 (https://forscan.org/forum/viewtopic.php?f=13&t=19552). You need to unzip and import the attached profile in the Vehicle->Profiles section. Please note the profile is fake so use it only for the APIM bench programming.
"
[Ford Focus EcoBoost Gasoline Turbocharged Direct Injection 2_3L 2017 ( 2017 MY ) VIN WF0_________03158.profile.zip](https://github.com/EtoTen/stm32_can_sim/files/14633400/Ford.Focus.EcoBoost.Gasoline.Turbocharged.Direct.Injection.2_3L.2017.2017.MY.VIN.WF0_________03158.profile.zip)

It is very touchy, and I personally had issues before getting that profile. It could be easier to get a used BCM, which would trick ForScan into thinking you are scanning a real car.

**Comment by svenhe88** [comment]
Awesome,

thanks for the quick nice support.
This is the game changer, works fine with loaded profile, no need for bcm.


BR & thanks!
